{% set name = "fypp" %}
{% set version = "3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b777ae70081c7c82edcf52eefc01a3e8a566b4e82ccd33ca3b2f06faf1d07d36

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - fypp = fypp:run_fypp

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip

test:
  commands:
    - fypp --help
  commands:
    - pip check

about:
  home: https://github.com/aradi/fypp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python powered Fortran preprocessor'

  description: |
    Fypp is a Python powered preprocessor. It can be used for any 
    programming languages but its primary aim is to offer a Fortran 
    preprocessor, which helps to extend Fortran with condititional 
    compiling and template metaprogramming capabilities.
  doc_url: http://fypp.readthedocs.org/
  dev_url: https://github.com/aradi/fypp

extra:
  recipe-maintainers:
    - jan-janssen
