travis:
  secure:
    BINSTAR_TOKEN: ijQQ156sYMQQoK1DEVMUc0kCT3rGOwXxZP5bL6JsucROOQ3DGL8KjQ8Qn5wGkLeD9k5mYHREmYA8qQ/vH4Kh7xfFoF+/8KGtLZ7D2bCe4oqa8j1aZ6aG3rlqOXcrWT5S9QaYe90Q1XT0WfKH18bofxL3BE9PXJU5XFj1jj8zH12WzszsCOCPJ2uUISDOGfaSieiFz2dahqgVMW/FVzXtodNnLmMkVIW3OaPwnf2QMHyABLizp0PH2G1GfiWOH259+geAhoDapfJ+lFa76H5teaIuStDULWQ+kurk/4LMCvrVccSZWlCM5oKQsjYIDLXJ/zZ8qR0sYx2p5YeTiEWWXuSBaIDx0ElaHtzY2pxHWnJcLIiNRYDazAZ2gFM+p+0hd2meRJHJcUh6H7Lia1+LQTjPO4Xg4aN12QRD75vd4RCBItAqgibXlqRPA2WBRs5aPHZVrnsi8dPNpvkqWnGZWgsmqFH3zaJueOvTf0aoAdr4lCtTd8QJKyk784KYnQ2vDn56xNcG81dkIdet7s6tEx7E+0C7cTxs0d6v5v6rNUvzdt2ujbzRUqSph/hVZv8UQSUiy3ra+4BHNeZ+UgR/XEA0QdzkJ9uaAWttAZPBXeMwSKWkVjjdEICtyaCvFiSvkHmlZGb7NIZ2fbXnYBLYW7gaiiJE4F5RaDryClG5bUI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
